export const ALL_COUNTRIES = "ALL_COUNTRIES"
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY'
export const GET_ID_COUNTRY = "GET_ID_COUNTRY"
export const ALL_ACTIVITIES = 'ALL_ACTIVITIES'
export const POST_ACTIVITY = 'POST_ACTIVITY'